<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>Torutek.SigSpec.CodeGeneration</PackageId>
  </PropertyGroup>
  <PropertyGroup>
    <Owners>torutek</Owners>
    <Authors>torutek, Rico Suter</Authors>
    <Description>Code generator for SignalR Core.</Description>
    <Version>0.3.0</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/torutek/SigSpec</PackageProjectUrl>
    <RepositoryUrl>https://github.com/torutek/SigSpec.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>SignalR Specification CodeGeneration</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="" Link="README.md" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NJsonSchema.CodeGeneration" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SigSpec.Core\SigSpec.Core.csproj" />
  </ItemGroup>
</Project>