<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>TorutekGithub.SigSpec.CodeGeneration.CSharp</PackageId>
  </PropertyGroup>
  <PropertyGroup>
    <Owners>torutek</Owners>
    <Authors>torutek, Rico Suter</Authors>
    <Version>0.3.0</Version>
    <Description>Code generator for SignalR Core.</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/torutek/SigSpec</PackageProjectUrl>
    <RepositoryUrl>https://github.com/torutek/SigSpec.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>SignalR Specification CodeGeneration CSharp</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="" Link="README.md" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Templates\Hub.liquid" />
    <None Remove="Templates\HubFile.liquid" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Templates\HubFile.liquid" />
    <EmbeddedResource Include="Templates\Hub.liquid" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NJsonSchema.CodeGeneration" />
    <PackageReference Include="NJsonSchema.CodeGeneration.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SigSpec.CodeGeneration\SigSpec.CodeGeneration.csproj" />
    <ProjectReference Include="..\SigSpec.Core\SigSpec.Core.csproj" />
  </ItemGroup>
</Project>