<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="NJsonSchema" Version="11.1.0" />
    <PackageVersion Include="NJsonSchema.CodeGeneration" Version="11.1.0" />
    <PackageVersion Include="NJsonSchema.CodeGeneration.CSharp" Version="11.1.0" />
    <PackageVersion Include="NJsonSchema.CodeGeneration.TypeScript" Version="11.1.0" />
    <PackageVersion Include="NJsonSchema.NewtonsoftJson" Version="11.1.0" />
    <PackageVersion Include="xunit" Version="2.7.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.7" />
  </ItemGroup>
</Project>